#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2023 Zscaler Inc, <devrel@zscaler.com>

#                             MIT License
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r"""
---
module: zia_atp_malware_policy
short_description: "Updates security exceptions for the Malware Protection policy"
description:
  - "Updates security exceptions for the Malware Protection policy"
author:
  - William Guilherme (@willguibr)
version_added: "2.0.0"
requirements:
    - Zscaler SDK Python can be obtained from PyPI U(https://pypi.org/project/zscaler-sdk-python/)
notes:
    - Check mode is not supported.
extends_documentation_fragment:
  - zscaler.ziacloud.fragments.provider
  - zscaler.ziacloud.fragments.documentation
  - zscaler.ziacloud.fragments.modified_state

options:
  block_unscannable_files:
    description:
      - Indicates whether to allow or block users from uploading or downloading files that the Zscaler service is unable to scan.
      - This might occur if the file is an unrecognized file format, an excessive size, or recursively compressed.
    type: bool
    required: false
  block_password_protected_archive_files:
    description: Indicates whether to allow or block users from uploading or downloading password-protected files
    required: false
    type: bool
"""

EXAMPLES = r"""
- name: Gets a list of rule label by name
  zscaler.ziacloud.zia_atp_malware_policy:
    provider: '{{ provider }}'
    block_unscannable_files: true
    block_password_protected_archive_files: true
"""

RETURN = r"""
#  Malicious Policy Configured.
"""

from traceback import format_exc
from ansible.module_utils._text import to_native
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.zscaler.ziacloud.plugins.module_utils.zia_client import (
    ZIAClientHelper,
)


def core(module):
    state = module.params.get("state")
    if state != "present":
        module.fail_json(msg="Only 'present' is supported for this module.")

    client = ZIAClientHelper(module)
    block_unscannable_files = module.params.get("block_unscannable_files")
    block_password_protected_archive_files = module.params.get(
        "block_password_protected_archive_files"
    )

    current_policy, _unused, error = (
        client.malware_protection_policy.get_atp_malware_policy()
    )
    if error:
        module.fail_json(
            msg=f"Error fetching malware protection policy: {to_native(error)}"
        )

    current_unscannable = current_policy.get("block_unscannable_files", False)
    current_protected = current_policy.get(
        "block_password_protected_archive_files", False
    )

    module.warn(
        f"üîç Current policy: block_unscannable_files={current_unscannable}, block_password_protected_archive_files={current_protected}"
    )
    module.warn(
        f"üì• Desired policy: block_unscannable_files={block_unscannable_files}, block_password_protected_archive_files={block_password_protected_archive_files}"
    )

    if module.check_mode:
        has_drift = (
            block_unscannable_files != current_unscannable
            or block_password_protected_archive_files != current_protected
        )
        module.exit_json(changed=has_drift)

    if (
        block_unscannable_files != current_unscannable
        or block_password_protected_archive_files != current_protected
    ):
        updated_policy, _unused, error = (
            client.malware_protection_policy.update_atp_malware_policy(
                block_unscannable_files, block_password_protected_archive_files
            )
        )
        if error:
            module.fail_json(
                msg=f"Error updating malware protection policy: {to_native(error)}"
            )

        module.exit_json(changed=True, malware_inspection=updated_policy)

    module.exit_json(changed=False, malware_inspection=current_policy)


def main():
    argument_spec = ZIAClientHelper.zia_argument_spec()
    argument_spec.update(
        block_unscannable_files=dict(type="bool", required=False),
        block_password_protected_archive_files=dict(type="bool", required=False),
        state=dict(type="str", choices=["present"], default="present"),
    )

    module = AnsibleModule(argument_spec=argument_spec, supports_check_mode=True)

    try:
        core(module)
    except Exception as e:
        module.fail_json(msg=to_native(e), exception=format_exc())


if __name__ == "__main__":
    main()
